import { ActivityMetrics, StickerStyle, StickerType } from './types';

export const DEFAULT_METRICS: ActivityMetrics = {
  title: 'Morning Run',
  distance: '8.43',
  unit: 'km',
  pace: '07:07',
  time: '1h 00m 00s',
  heartRate: '158',
  elevation: '36',
  calories: '504',
  date: '24 AUG 2026',
  timeOfDay: '5:43 AM',
  location: 'Central Jakarta',
  gear: 'Diadora Ntzno',
  splits: [
    { km: 1, pace: '07:32' },
    { km: 2, pace: '07:19' },
    { km: 3, pace: '07:13' },
    { km: 4, pace: '07:04' },
    { km: 5, pace: '06:55' },
    { km: 6, pace: '06:52' },
    { km: 7, pace: '07:00' },
    { km: 8, pace: '07:07' },
  ],
};

export const MOCK_DATASETS: Record<string, ActivityMetrics> = {
  morning_run: DEFAULT_METRICS,
  half_marathon: {
    title: 'Half Marathon Race',
    distance: '21.10',
    unit: 'km',
    pace: '05:30',
    time: '1h 56m 03s',
    heartRate: '168',
    elevation: '120',
    calories: '1420',
    date: '15 OCT 2026',
    timeOfDay: '6:00 AM',
    location: 'Jakarta Marathon',
    gear: 'Nike Vaporfly',
    splits: [
      { km: 1, pace: '05:40' },
      { km: 5, pace: '05:32' },
      { km: 10, pace: '05:28' },
      { km: 15, pace: '05:25' },
      { km: 20, pace: '05:35' },
    ],
  },
  interval_workout: {
    title: '5x1000m Track Intervals',
    distance: '6.50',
    unit: 'km',
    pace: '04:15',
    time: '27m 30s',
    heartRate: '175',
    elevation: '5',
    calories: '480',
    date: '18 AUG 2026',
    timeOfDay: '6:30 PM',
    location: 'GBK Track Stadium',
    gear: 'Adidas Takumi Sen',
    splits: [
      { km: 1, pace: '04:12' },
      { km: 2, pace: '04:15' },
      { km: 3, pace: '04:10' },
      { km: 4, pace: '04:18' },
      { km: 5, pace: '04:08' },
    ],
  },
  trail_run: {
    title: 'Mountain Ridge Trail',
    distance: '14.80',
    unit: 'km',
    pace: '08:45',
    time: '2h 09m 30s',
    heartRate: '152',
    elevation: '680',
    calories: '1150',
    date: '02 SEP 2026',
    timeOfDay: '7:15 AM',
    location: 'Mount Gede Trail',
    gear: 'Hoka Speedgoat',
    splits: [
      { km: 1, pace: '07:50' },
      { km: 5, pace: '09:20' },
      { km: 10, pace: '09:40' },
      { km: 14, pace: '08:10' },
    ],
  },
};

const BASE_STYLE: StickerStyle = {
  textColor: '#ffffff',
  backgroundColor: 'rgba(24,24,27,0.9)',
  borderColor: 'rgba(255,255,255,0.1)',
  accentColor: '#00E5FF',
  fontFamily: 'sans',
  fontSize: 14,
  opacity: 1,
  borderRadius: 12,
};

export const DEFAULT_STYLES: Record<StickerType, StickerStyle> = {
  red_bold_header: { ...BASE_STYLE, textColor: '#ef4444', backgroundColor: 'transparent' },
  elevation_gradient: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: 'linear-gradient(to top, rgba(0,0,0,0.8), transparent)' },
  minimal_horizontal: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: 'transparent' },
  serif_classic: { ...BASE_STYLE, textColor: '#ffffff', fontFamily: 'serif' },
  digital_red_led: { ...BASE_STYLE, textColor: '#ef4444', backgroundColor: '#18181b', fontFamily: 'led' },
  barcode_ticket: { ...BASE_STYLE, textColor: '#000000', backgroundColor: '#ffffff', fontFamily: 'mono', borderRadius: 4 },
  color_badge: { ...BASE_STYLE, textColor: '#000000', backgroundColor: '#eab308' },
  runner_bold: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: 'transparent' },
  splits_list: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b' },
  finish_banner: { ...BASE_STYLE, textColor: '#000000', backgroundColor: '#ffffff', borderRadius: 4 },
  receipt: { ...BASE_STYLE, textColor: '#18181b', backgroundColor: '#fafafa', borderColor: '#e4e4e7', fontFamily: 'mono', borderRadius: 8 },
  json_code: { ...BASE_STYLE, textColor: '#4ade80', backgroundColor: '#09090b', borderColor: '#27272a', fontFamily: 'mono', borderRadius: 12 },
  speedometer: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', accentColor: '#ef4444' },
  splits_histogram: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b' },
  polyline_track: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: 'transparent' },
  windows_error: { ...BASE_STYLE, textColor: '#000000', backgroundColor: '#c0c0c0', borderColor: '#ffffff', borderRadius: 2 },
  mbanking: { ...BASE_STYLE, textColor: '#0f172a', backgroundColor: '#ffffff', borderColor: '#22c55e', borderRadius: 16 },
  getty_stamp: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: 'rgba(0,0,0,0.8)', borderRadius: 4 },
  cigarette_warning: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#000000', borderColor: '#ffffff', borderRadius: 0 },
  imessage: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#3b82f6', borderRadius: 20 },
  ios_call: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: 'rgba(30,30,35,0.9)', borderRadius: 16 },
  sticky_note: { ...BASE_STYLE, textColor: '#1c1917', backgroundColor: '#fef08a', borderColor: '#fde047', fontFamily: 'handwritten', borderRadius: 4 },
  nutrition_facts: { ...BASE_STYLE, textColor: '#000000', backgroundColor: '#ffffff', borderColor: '#000000', borderRadius: 4 },
  instagram_post: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderRadius: 12 },
  serif_magazine: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: 'rgba(0,0,0,0.5)', fontFamily: 'serif', borderRadius: 8 },
  marathon_milestone: { ...BASE_STYLE, textColor: '#000000', backgroundColor: '#facc15', borderRadius: 8 },
  cadence_rpm: { ...BASE_STYLE, textColor: '#38bdf8', backgroundColor: '#0f172a', borderRadius: 12 },
  hr_zone_meter: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#1e293b', borderRadius: 10 },
  newspaper_headline: { ...BASE_STYLE, textColor: '#18181b', backgroundColor: '#fef3c7', fontFamily: 'serif', borderRadius: 0 },
  spotify_player: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#121212', borderRadius: 16 },
  airport_boarding_pass: { ...BASE_STYLE, textColor: '#0f172a', backgroundColor: '#ffffff', fontFamily: 'mono', borderRadius: 8 },
  cassette_tape: { ...BASE_STYLE, textColor: '#18181b', backgroundColor: '#fbbf24', borderRadius: 6 },
  polaroid_frame: { ...BASE_STYLE, textColor: '#18181b', backgroundColor: '#ffffff', borderRadius: 2 },
  cyberpunk_neon: { ...BASE_STYLE, textColor: '#00ffcc', backgroundColor: '#050515', borderColor: '#00ffcc', fontFamily: 'mono', borderRadius: 4 },
  workout_summary_grid: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#09090b', borderRadius: 16 },
  weekly_recap_ring: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderRadius: 20 },
  icon_badge: { ...BASE_STYLE, textColor: '#00E5FF', backgroundColor: 'rgba(0,0,0,0.7)', borderRadius: 9999 },
};
