import { ActivityMetrics, StickerStyle, StickerType } from './types';

// ─── 11 DISTINCT VISUAL MOOD VARIANTS ──────────────────────
// Each variant creates a completely different visual feel
export interface StyleVariant {
  id: string;
  label: string;
  bg: string;
  text: string;
  accent: string;
  border: string;
  mood: string;
  fontFamily: string;
  fontSize: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
  textTransform: 'none' | 'uppercase' | 'lowercase' | 'capitalize';
  borderRadius: string;
  decoration: 'none' | 'dots' | 'stripes' | 'glow' | 'shadow' | 'outline' | 'gradient' | 'emboss' | 'scanlines' | 'vignette' | 'noise';
  letterSpacing: string;
  fontWeight: string;
}

export const STYLE_VARIANTS: StyleVariant[] = [
  { id: 'default',    label: 'Default',     bg: '#18181b', text: '#ffffff', accent: '#00E5FF', border: '#27272a', mood: 'dark',   fontFamily: 'Inter, sans-serif',          fontSize: 'sm', textTransform: 'none',     borderRadius: '12px', decoration: 'none',      letterSpacing: '0em',   fontWeight: '400' },
  { id: 'neon',       label: 'Neon',        bg: '#050515', text: '#00ffcc', accent: '#00ffcc', border: '#00ffcc', mood: 'glow',   fontFamily: 'JetBrains Mono, monospace', fontSize: 'xs', textTransform: 'uppercase', borderRadius: '0px',  decoration: 'glow',      letterSpacing: '0.05em', fontWeight: '700' },
  { id: 'cyberpunk',  label: 'Cyberpunk',   bg: '#0d0221', text: '#ff007f', accent: '#ff007f', border: '#ff007f', mood: 'neon',   fontFamily: '"Press Start 2P", cursive',  fontSize: 'xs', textTransform: 'uppercase', borderRadius: '0px',  decoration: 'scanlines', letterSpacing: '0.08em', fontWeight: '400' },
  { id: 'gold',       label: 'Retro Gold',  bg: '#1c1917', text: '#facc15', accent: '#f59e0b', border: '#ca8a04', mood: 'warm',   fontFamily: 'Caveat, cursive',            fontSize: 'lg', textTransform: 'capitalize',borderRadius: '8px',  decoration: 'emboss',    letterSpacing: '0.02em', fontWeight: '600' },
  { id: 'mono',       label: 'Monochrome',  bg: '#000000', text: '#ffffff', accent: '#ffffff', border: '#ffffff', mood: 'clean',  fontFamily: 'JetBrains Mono, monospace', fontSize: 'xs', textTransform: 'uppercase', borderRadius: '0px',  decoration: 'dots',      letterSpacing: '0.1em',  fontWeight: '300' },
  { id: 'pastel',     label: 'Pastel',      bg: '#fef08a', text: '#1c1917', accent: '#fde047', border: '#fde047', mood: 'soft',   fontFamily: 'Caveat, cursive',            fontSize: 'xl', textTransform: 'none',     borderRadius: '20px', decoration: 'shadow',    letterSpacing: '0em',   fontWeight: '400' },
  { id: 'crimson',    label: 'Crimson',     bg: '#450a0a', text: '#fca5a5', accent: '#ef4444', border: '#ef4444', mood: 'bold',   fontFamily: 'Inter, sans-serif',          fontSize: 'sm', textTransform: 'uppercase', borderRadius: '4px',  decoration: 'outline',   letterSpacing: '0.06em', fontWeight: '900' },
  { id: 'ocean',      label: 'Ocean',       bg: '#0c4a6e', text: '#e0f2fe', accent: '#38bdf8', border: '#0284c7', mood: 'cool',   fontFamily: 'Inter, sans-serif',          fontSize: 'sm', textTransform: 'none',     borderRadius: '16px', decoration: 'gradient',  letterSpacing: '0em',   fontWeight: '500' },
  { id: 'forest',     label: 'Forest',      bg: '#022c22', text: '#d1fae5', accent: '#34d399', border: '#059669', mood: 'nature', fontFamily: 'Caveat, cursive',            fontSize: 'lg', textTransform: 'none',     borderRadius: '12px', decoration: 'noise',     letterSpacing: '0.01em', fontWeight: '600' },
  { id: 'sunset',     label: 'Sunset',      bg: '#431407', text: '#ffedd5', accent: '#fb923c', border: '#ea580c', mood: 'warm',   fontFamily: 'Inter, sans-serif',          fontSize: 'md', textTransform: 'capitalize',borderRadius: '8px',  decoration: 'vignette',  letterSpacing: '0.03em', fontWeight: '700' },
  { id: 'midnight',   label: 'Midnight',    bg: '#1e1b4b', text: '#e0e7ff', accent: '#818cf8', border: '#6366f1', mood: 'elegant',fontFamily: '"Press Start 2P", cursive',  fontSize: 'xs', textTransform: 'none',     borderRadius: '4px',  decoration: 'stripes',   letterSpacing: '0.04em', fontWeight: '400' },
];

export const DEFAULT_METRICS: ActivityMetrics = {
  title: 'Morning Run',
  distance: '8.43',
  unit: 'km',
  pace: '07:07',
  time: '1h 00m 00s',
  heartRate: '158',
  elevation: '36',
  calories: '504',
  date: '24 AUG 2026',
  timeOfDay: '5:43 AM',
  location: 'Central Jakarta',
  gear: 'Diadora Ntzno',
  splits: [
    { km: 1, pace: '07:32' },
    { km: 2, pace: '07:19' },
    { km: 3, pace: '07:13' },
    { km: 4, pace: '07:04' },
    { km: 5, pace: '06:55' },
    { km: 6, pace: '06:52' },
    { km: 7, pace: '07:00' },
    { km: 8, pace: '07:07' },
  ],
};

export const MOCK_DATASETS: Record<string, ActivityMetrics> = {
  morning_run: DEFAULT_METRICS,
  half_marathon: {
    title: 'Half Marathon Race',
    distance: '21.10',
    unit: 'km',
    pace: '05:30',
    time: '1h 56m 03s',
    heartRate: '168',
    elevation: '120',
    calories: '1420',
    date: '15 OCT 2026',
    timeOfDay: '6:00 AM',
    location: 'Jakarta Marathon',
    gear: 'Nike Vaporfly',
    splits: [
      { km: 1, pace: '05:40' },
      { km: 5, pace: '05:32' },
      { km: 10, pace: '05:28' },
      { km: 15, pace: '05:25' },
      { km: 20, pace: '05:35' },
    ],
  },
  interval_workout: {
    title: '5x1000m Track Intervals',
    distance: '6.50',
    unit: 'km',
    pace: '04:15',
    time: '27m 30s',
    heartRate: '175',
    elevation: '5',
    calories: '480',
    date: '18 AUG 2026',
    timeOfDay: '6:30 PM',
    location: 'GBK Track Stadium',
    gear: 'Adidas Takumi Sen',
    splits: [
      { km: 1, pace: '04:12' },
      { km: 2, pace: '04:15' },
      { km: 3, pace: '04:10' },
      { km: 4, pace: '04:18' },
      { km: 5, pace: '04:08' },
    ],
  },
  trail_run: {
    title: 'Mountain Ridge Trail',
    distance: '14.80',
    unit: 'km',
    pace: '08:45',
    time: '2h 09m 30s',
    heartRate: '152',
    elevation: '680',
    calories: '1150',
    date: '02 SEP 2026',
    timeOfDay: '7:15 AM',
    location: 'Mount Gede Trail',
    gear: 'Hoka Speedgoat',
    splits: [
      { km: 1, pace: '07:50' },
      { km: 5, pace: '09:20' },
      { km: 10, pace: '09:40' },
      { km: 14, pace: '08:10' },
    ],
  },
};

const BASE_STYLE: StickerStyle = {
  textColor: '#ffffff',
  backgroundColor: 'rgba(24,24,27,0.9)',
  borderColor: 'rgba(255,255,255,0.1)',
  accentColor: '#00E5FF',
  fontFamily: 'sans',
  fontSize: 14,
  opacity: 1,
  borderRadius: 12,
};

export const DEFAULT_STYLES: Record<StickerType, StickerStyle> = {
  red_bold_header: { ...BASE_STYLE, textColor: '#ef4444', backgroundColor: 'transparent' },
  elevation_gradient: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: 'linear-gradient(to top, rgba(0,0,0,0.8), transparent)' },
  minimal_horizontal: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: 'transparent' },
  serif_classic: { ...BASE_STYLE, textColor: '#ffffff', fontFamily: 'serif' },
  digital_red_led: { ...BASE_STYLE, textColor: '#ef4444', backgroundColor: '#18181b', fontFamily: 'led' },
  barcode_ticket: { ...BASE_STYLE, textColor: '#000000', backgroundColor: '#ffffff', fontFamily: 'mono', borderRadius: 4 },
  color_badge: { ...BASE_STYLE, textColor: '#000000', backgroundColor: '#eab308' },
  runner_bold: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: 'transparent' },
  splits_list: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b' },
  finish_banner: { ...BASE_STYLE, textColor: '#000000', backgroundColor: '#ffffff', borderRadius: 4 },
  receipt: { ...BASE_STYLE, textColor: '#18181b', backgroundColor: '#fafafa', borderColor: '#e4e4e7', fontFamily: 'mono', borderRadius: 8 },
  json_code: { ...BASE_STYLE, textColor: '#4ade80', backgroundColor: '#09090b', borderColor: '#27272a', fontFamily: 'mono', borderRadius: 12 },
  speedometer: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', accentColor: '#ef4444' },
  splits_histogram: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b' },
  polyline_track: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: 'transparent' },
  windows_error: { ...BASE_STYLE, textColor: '#000000', backgroundColor: '#c0c0c0', borderColor: '#ffffff', borderRadius: 2 },
  mbanking: { ...BASE_STYLE, textColor: '#0f172a', backgroundColor: '#ffffff', borderColor: '#22c55e', borderRadius: 16 },
  getty_stamp: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: 'rgba(0,0,0,0.8)', borderRadius: 4 },
  cigarette_warning: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#000000', borderColor: '#ffffff', borderRadius: 0 },
  imessage: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#3b82f6', borderRadius: 20 },
  ios_call: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: 'rgba(30,30,35,0.9)', borderRadius: 16 },
  sticky_note: { ...BASE_STYLE, textColor: '#1c1917', backgroundColor: '#fef08a', borderColor: '#fde047', fontFamily: 'handwritten', borderRadius: 4 },
  nutrition_facts: { ...BASE_STYLE, textColor: '#000000', backgroundColor: '#ffffff', borderColor: '#000000', borderRadius: 4 },
  instagram_post: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderRadius: 12 },
  serif_magazine: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: 'rgba(0,0,0,0.5)', fontFamily: 'serif', borderRadius: 8 },
  marathon_milestone: { ...BASE_STYLE, textColor: '#000000', backgroundColor: '#facc15', borderRadius: 8 },
  cadence_rpm: { ...BASE_STYLE, textColor: '#38bdf8', backgroundColor: '#0f172a', borderRadius: 12 },
  hr_zone_meter: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#1e293b', borderRadius: 10 },
  newspaper_headline: { ...BASE_STYLE, textColor: '#18181b', backgroundColor: '#fef3c7', fontFamily: 'serif', borderRadius: 0 },
  spotify_player: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#121212', borderRadius: 16 },
  airport_boarding_pass: { ...BASE_STYLE, textColor: '#0f172a', backgroundColor: '#ffffff', fontFamily: 'mono', borderRadius: 8 },
  cassette_tape: { ...BASE_STYLE, textColor: '#18181b', backgroundColor: '#fbbf24', borderRadius: 6 },
  polaroid_frame: { ...BASE_STYLE, textColor: '#18181b', backgroundColor: '#ffffff', borderRadius: 2 },
  cyberpunk_neon: { ...BASE_STYLE, textColor: '#00ffcc', backgroundColor: '#050515', borderColor: '#00ffcc', fontFamily: 'mono', borderRadius: 4 },
  workout_summary_grid: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#09090b', borderRadius: 16 },
  weekly_recap_ring: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderRadius: 20 },
  icon_badge: { ...BASE_STYLE, textColor: '#00E5FF', backgroundColor: 'rgba(15,23,42,0.9)', borderColor: 'rgba(0,229,255,0.3)', borderRadius: 16 },
  minimal_minimalist: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: 'rgba(0,0,0,0.7)', borderRadius: 9999 },
  retro_badge: { ...BASE_STYLE, textColor: '#fb923c', backgroundColor: '#1c1917', borderColor: '#ea580c', borderRadius: 12 },
  futuristic_glass: { ...BASE_STYLE, textColor: '#38bdf8', backgroundColor: 'rgba(15,23,42,0.75)', borderColor: '#0284c7', borderRadius: 16 },
  minimal_circle: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#09090b', borderColor: '#3f3f46', borderRadius: 9999 },
  compact_split: { ...BASE_STYLE, textColor: '#a855f7', backgroundColor: '#18181b', borderColor: '#7e22ce', borderRadius: 8 },
  parametric: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  elevation_wave: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#0c0c0c', borderColor: '#1f1f1f', borderRadius: 12 },
  horizontal_metrics: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 9999 },
  serif_italic: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#0f0f0f', fontFamily: 'serif', borderColor: '#1f1f1f', borderRadius: 12 },
  receipt_full: { ...BASE_STYLE, textColor: '#1c1917', backgroundColor: '#fafafa', borderColor: '#d6d3d1', fontFamily: 'mono', borderRadius: 4 },
  splits_roman: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  text_sentence: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  large_typography: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#09090b', borderColor: '#27272a', borderRadius: 12 },
  data_table: { ...BASE_STYLE, textColor: '#d4d4d4', backgroundColor: '#09090b', fontFamily: 'mono', borderColor: '#27272a', borderRadius: 8 },
  bar_chart_pace: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  location_card: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  day_badge: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  dual_stats: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  column_numbers: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  highlight_blocks: { ...BASE_STYLE, textColor: '#000000', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  cumulative_list: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', fontFamily: 'mono', borderColor: '#27272a', borderRadius: 12 },
  verified_badge: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  time_range: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  pace_chart: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#0f172a', borderColor: '#1e293b', borderRadius: 12 },
  italic_title: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', fontFamily: 'serif', borderColor: '#27272a', borderRadius: 12 },
  location_pill: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 9999 },
  map_route: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#09090b', borderColor: '#27272a', borderRadius: 12 },
  square_frame: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: 'transparent', borderColor: '#3b82f6', borderRadius: 0 },
  colored_bar: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 8 },
  data_rows: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  calendar_card: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  weekly_list: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  description_card: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', fontFamily: 'serif', borderColor: '#27272a', borderRadius: 12 },
  pace_zones: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  elevation_area: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  text_paragraph: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  highlight_bar: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#3b82f6', borderColor: '#2563eb', borderRadius: 9999 },
  kilometres_bold: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  trademark_style: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  heart_pill: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#ef4444', borderColor: '#dc2626', borderRadius: 9999 },
  led_clock: { ...BASE_STYLE, textColor: '#ef4444', backgroundColor: '#0a0a0a', fontFamily: 'led', borderColor: '#1f1f1f', borderRadius: 12 },
  bold_location: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  route_number: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  app_widget: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  money_tag: { ...BASE_STYLE, textColor: '#000000', backgroundColor: '#facc15', borderColor: '#eab308', borderRadius: 9999 },
  multilingual: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  simple_table: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  repeat_text: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  monthly_total: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  weekly_dots: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  weekly_summary: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  weekly_table: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  circle_grid: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  monthly_chart: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  progress_pct: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  area_chart_weekly: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  dot_progress: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  square_progress: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  vertical_bars: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  stacked_days: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  running_total: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  weekly_map: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  gradient_mesh: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#667eea', borderRadius: 12 },
  neo_brutalist: { ...BASE_STYLE, textColor: '#000000', backgroundColor: '#ffffff', borderColor: '#000000', borderRadius: 0 },
  glass_card: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: 'rgba(255,255,255,0.1)', borderColor: 'rgba(255,255,255,0.2)', borderRadius: 16 },
  neon_glow: { ...BASE_STYLE, textColor: '#00ffcc', backgroundColor: '#050515', borderColor: '#00ffcc', fontFamily: 'mono', borderRadius: 8 },
  film_strip: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#000000', borderColor: '#333333', borderRadius: 4 },
  newspaper_column: { ...BASE_STYLE, textColor: '#1c1917', backgroundColor: '#fef3c7', fontFamily: 'serif', borderRadius: 0 },
  terminal_green: { ...BASE_STYLE, textColor: '#22c55e', backgroundColor: '#0a0a0a', fontFamily: 'mono', borderColor: '#1a3a1a', borderRadius: 4 },
  vhs_retro: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#1a1a2e', borderColor: '#333333', borderRadius: 8 },
  notebook_line: { ...BASE_STYLE, textColor: '#1c1917', backgroundColor: '#fefce8', fontFamily: 'handwritten', borderRadius: 4 },
  blueprint: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#1e3a5f', fontFamily: 'mono', borderColor: '#2563eb', borderRadius: 4 },
  embossed: { ...BASE_STYLE, textColor: '#d4d4d4', backgroundColor: '#f5f5f4', borderRadius: 8 },
  metallic: { ...BASE_STYLE, textColor: '#404040', backgroundColor: '#b0b0b0', fontFamily: 'mono', borderRadius: 8 },
  pixel_art: { ...BASE_STYLE, textColor: '#22c55e', backgroundColor: '#000000', fontFamily: 'led', borderRadius: 0 },
  achievement: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#1a1a2e', borderColor: '#facc15', borderRadius: 8 },
  leaderboard: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  countdown: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  progress_ring: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#09090b', borderColor: '#27272a', borderRadius: 9999 },
  radial_chart: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  heatmap: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  timeline: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  tab_ui: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  card_stack: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  ribbon: { ...BASE_STYLE, textColor: '#000000', backgroundColor: '#facc15', borderRadius: 4 },
  notification: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#27272a', borderRadius: 16 },
  music_player: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#1a1a2e', borderColor: '#2d2d44', borderRadius: 12 },
  weather_card: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  splits_bar_chart: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  stacked_metrics: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  running_man: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  bordered_frame: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#09090b', borderColor: '#ffffff', borderRadius: 12 },
  stat_ribbon: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderRadius: 0 },
  dot_matrix: { ...BASE_STYLE, textColor: '#44403c', backgroundColor: '#f5f5dc', fontFamily: 'mono', borderRadius: 4 },
  badge_collection: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  mini_map: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  progress_bar: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  circular_gauge: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  grid_4x4: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 0 },
  quote_card: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', fontFamily: 'serif', borderColor: '#27272a', borderRadius: 12 },
  comparison_split: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 0 },
  stacked_cards: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  floating_labels: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  asymmetric_layout: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 0 },
  minimalist_line: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  card_flip: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 0 },
  masonry_grid: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 8 },
  hexagon_badge: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  diamond_shape: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  triangle_layout: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  arch_frame: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  circle_cutout: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  rounded_stripes: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  gradient_border: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  inner_shadow: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  double_frame: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  zigzag_edge: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  wave_bottom: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  corner_fold: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  tabbed_card: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  accordion: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  split_diagonal: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  dot_pattern: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  cross_stitch: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  chevron_rows: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 0 },
  pinstripe: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  brick_layout: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  tile_mosaic: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  stained_glass: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  paper_texture: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  carbon_fiber: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#1a1a1a', borderColor: '#333333', borderRadius: 12 },
  brushed_metal: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#2a2a2a', borderColor: '#444444', borderRadius: 12 },
  denim_fabric: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#1a3a5c', borderColor: '#2a5a8c', borderRadius: 12 },
  concrete_wall: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#3a3a3a', borderColor: '#555555', borderRadius: 12 },
  rustic_wood: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#3d2b1f', borderColor: '#5a4030', borderRadius: 12 },
  bamboo_weave: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#2d4a2d', borderColor: '#3d6a3d', borderRadius: 12 },
  woven_pattern: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#2a2a3a', borderColor: '#3a3a4a', borderRadius: 12 },
  leather_grain: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#2a1a0a', borderColor: '#4a3a2a', borderRadius: 12 },
  silk_sheen: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  velvet_plush: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  satin_finish: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  matte_paper: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  glossy_surface: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  translucent_glass: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: 'rgba(24,24,27,0.8)', borderColor: '#27272a', borderRadius: 12 },
  frosted_glass: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: 'rgba(24,24,27,0.5)', borderColor: 'rgba(39,39,42,0.5)', borderRadius: 12 },
  smoked_glass: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: 'rgba(0,0,0,0.7)', borderColor: 'rgba(255,255,255,0.1)', borderRadius: 12 },
  cracked_ice: { ...BASE_STYLE, textColor: '#333333', backgroundColor: '#e8f4f8', borderColor: '#b8d4e8', borderRadius: 12 },
  liquid_metal: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#1a1a2e', borderColor: '#0f3460', borderRadius: 12 },
  holographic: { ...BASE_STYLE, textColor: '#000000', backgroundColor: 'linear-gradient(135deg, #ff6b6b, #feca57, #48dbfb, #ff9ff3, #54a0ff)', borderColor: 'rgba(255,255,255,0.3)', borderRadius: 12 },
  iridescent: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: 'linear-gradient(135deg, #667eea, #764ba2)', borderColor: 'rgba(255,255,255,0.2)', borderRadius: 12 },
  prismatic: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: 'linear-gradient(90deg, #ff0000, #ff8800, #ffff00, #00ff00, #0088ff, #8800ff)', borderColor: 'rgba(255,255,255,0.2)', borderRadius: 12 },
  nebula_cloud: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#0a001a', borderColor: '#2a0a4a', borderRadius: 12 },
  aurora_borealis: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#0a0a2e', borderColor: '#2ecc71', borderRadius: 12 },
  galaxy_spiral: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#000011', borderColor: '#112244', borderRadius: 12 },
  star_field: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#000022', borderColor: '#222244', borderRadius: 12 },
  sun_flare: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#1a0a00', borderColor: '#3a2a1a', borderRadius: 12 },
  moon_glow: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#0a0a1a', borderColor: '#1a1a3a', borderRadius: 12 },
  water_ripple: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#0a1a2a', borderColor: '#1a3a5a', borderRadius: 12 },
  flame_wave: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#1a0a00', borderColor: '#ff4400', borderRadius: 12 },
  electric_spark: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#0a0a1a', borderColor: '#00ff88', borderRadius: 12 },
  laser_grid: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#0a0a0a', borderColor: '#ff0044', borderRadius: 12 },
  radar_sweep: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#0a1a0a', borderColor: '#00ff44', borderRadius: 12 },
  sonar_ping: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#001a33', borderColor: '#0066cc', borderRadius: 12 },
  target_lock: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#1a0a0a', borderColor: '#ff4444', borderRadius: 12 },
  scope_view: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#0a0a0a', borderColor: '#333333', borderRadius: 12 },
  xray_vision: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#000000', borderColor: '#00aaff', borderRadius: 12 },
  thermal_map: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: 'linear-gradient(135deg, #0000ff, #00ff00, #ffff00, #ff0000)', borderColor: '#ff0000', borderRadius: 12 },
  night_vision: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#001a00', borderColor: '#00ff00', borderRadius: 12 },
  blueprint_grid: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#0a1a3a', borderColor: '#3388cc', borderRadius: 12 },
  schematic: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#1a1a1a', borderColor: '#00ff00', fontFamily: 'mono', borderRadius: 12 },
  circuit_board: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#0a2a0a', borderColor: '#00aa00', borderRadius: 12 },
  motherboard: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#0a1a0a', borderColor: '#00cc00', borderRadius: 12 },
  chip_layout: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#0a0a0a', borderColor: '#666666', borderRadius: 12 },
  wire_frame: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#00E5FF', borderRadius: 0 },
  mesh_network: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  node_graph: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  data_flow: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  pipeline: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  circuit_path: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
  trace_line: { ...BASE_STYLE, textColor: '#ffffff', backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: 12 },
};
